"""empty message

Revision ID: a162f204730b
Revises: 3844a91dd740
Create Date: 2025-12-20 13:40:54.455497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a162f204730b'
down_revision = '3844a91dd740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Appointment', schema=None) as batch_op:
        batch_op.drop_column('dept')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
