name: CI/CD to ECS
on: 
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: wecare
  ECS_CLUSTER: wecare-cluster
  ECS_SERVICE: wecare-service-lcx0jzxf
  ECS_TASK_DEFINITION: wecare


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr 
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set ECR image URI
        run: |
          echo "ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}" >> $GITHUB_ENV


      - name: Build Docker image
        run: |
          docker build -t wecare:${{ github.sha }} .

      - name: Tag image
        run: |
          docker tag wecare:${{ github.sha }}  $ECR_URI:${{ github.sha }} 

      - name: Push image to ECR
        run: | 
          docker push $ECR_URI:${{ github.sha }} 

      - name: Download task definition
        run: |
            aws ecs describe-task-definition \
            --task-definition $ECS_TASK_DEFINITION \
            --query taskDefinition > task-definition.json

      - name: Update image in task definition
        run: |
            sed -i "s|image\": \".*\"|image\": \"${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}\"|g" task-definition.json

      - name: Register new task definition
        run: |
            aws ecs register-task-definition \
            --cli-input-json file://task-definition.json

      - name: Update ECS service
        run: |
            aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment

#   deploy:
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to EC2
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_SSH_KEY }}

#           script: |
#             aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
#             | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

#             cd /home/ubuntu

#             if [ ! -d "node-app" ]; then
#                 git clone https://github.com/ehsanifrah/node-app.git
#             fi
            
#             cd node-app
#             git pull
#             #git fetch origin
#             #git reset --hard origin/main

#             # Install Docker Compose if not installed
#             # if ! docker compose version >/dev/null 2>&1; then
#             #     echo "Installing Docker Compose..."
#             #     sudo apt update
#             #     sudo apt install -y docker-composepull
#             # fi
            
#             export IMAGE_TAG=${{ github.sha }}

#             docker-compose down
#             docker-compose pull
#             docker-compose up -d --force-recreate